API_KEY = "nmVHci1xILw2O5FBIkVMQ5n364AnkxpiUTSPsfplZ0t1RjhYAlXXuBUQwNnBZZOD"
API_SECURITY = "wiMAMK3G3FSSvUtCuuyrMULQtdKqRXmQoNqNJ3JW8bVuE8YdyQVBcnjfadNBZhI9"

SYMBOL = "ETHUSDT"
POSITION_SIZE = 0.00047

#gridbot settings
NUM_BUY_GRID_LINES = 2
NUM_SELL_GRID_LINES = 1
GRID_SIZE = 0.007

CHECK_ORDERS_FREQUENCY = 1
CLOSED_ORDER_STATUS = "FILLED"

STOP_LOSS = 0.05

